# Generated by Django 5.0.6 on 2024-05-14 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cad_usuarios', '0002_rename_usuarios_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='sobrenome',
            field=models.Field(max_length=100),
        ),
    ]
